import Footer from "@/components/Shared-components/Footer/Footer";
import NavBarLayout from "@/components/Shared-components/NavBar/NavBarLayout";
import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="relative font-Shabnam">
        <NavBarLayout />
        {children}
        <Footer />
      </body>
    </html>
  );
}
